### ISSUE TITLE
Smart Enter No Longer Working

### ISSUE THREAD

**Issue by mabourehab** [Rolv-Apneseth/bypass.yazi#13]
Hello!

It unfortunately seems that the new Yazi 25.5.28 broke the smart enter feature.

I can no longer open up the files, but I can still navigate through directories and sub-directories.

I made sure  I am using the new mgr in keymap.toml. Seems a lot of stuff have been deprecated with the last update, but should not be breaking yet. Not sure what could be the problem. 

I installed smart-enter as a workaround for now.

Let me know what information you may need.

Thanks!

**Comment by Rolv-Apneseth** [comment]
Strange, it's working for me after testing changes on the new version. You're using the keybind suggested in the readme?

```toml
[[mgr.prepend_keymap]]
on = [ "l" ]
run = "plugin bypass smart-enter"
desc = "Open a file, or recursively enter child directory, skipping children with only a single subdirectory"
```

Maybe make sure the plugin is updated too. Not sure what else would cause it.
